Add common chain elements
networkservicemesh/sdk-sriov pull request #26
Opened 2020-09-17 12:57 UTC by Bolodya1997

Add resourcepool, vfconfig chain elements

2020-09-20 14:34 UTC, haiodo commented on pkg/networkservice/common/resourcepool/context.go
> +func GetResourcePool(ctx context.Context) PCIResourcePool {
```suggestion
func ResourcePool(ctx context.Context) PCIResourcePool {
```

Usually we are not using `Get`

2020-09-20 14:35 UTC, haiodo commented on pkg/networkservice/common/resourcepool/server.go
> +	service, capability, err := getServiceAndCapability(request)
I think you need to take ResourcePool here and check it passed, fail fast in case if not.

2020-09-20 14:36 UTC, haiodo commented on pkg/networkservice/common/vfconfig/server.go
> +	config := s.configs[conn.GetId()]
What if few parallel Close will occur?

2020-09-20 14:36 UTC, haiodo requested changes
Please check messages. Thanks

2020-09-21 11:26 UTC, Bolodya1997 commented on pkg/networkservice/common/resourcepool/context.go
> +func GetResourcePool(ctx context.Context) PCIResourcePool {
Renamed

2020-09-21 11:26 UTC, Bolodya1997 commented on pkg/networkservice/common/resourcepool/server.go
> +	service, capability, err := getServiceAndCapability(request)
Yep

2020-09-21 11:26 UTC, Bolodya1997 commented on pkg/networkservice/common/vfconfig/server.go
> +	config := s.configs[conn.GetId()]
Replaced `map` with `sync.Map`

2020-09-24 06:33 UTC, haiodo commented on pkg/networkservice/common/resourcepool/server.go
> +	for _, binder := range s.binders[igid] {
Should we unbind driver if all from group are free?

2020-09-24 06:33 UTC, haiodo commented on pkg/networkservice/common/resourcepool/server.go
> +	rv, err := next.Server(ctx).Close(ctx, conn)
Should we unbind driver if all from group are free?

2020-09-24 06:39 UTC, Bolodya1997 commented on pkg/networkservice/common/resourcepool/server.go
> +	rv, err := next.Server(ctx).Close(ctx, conn)
We can do it lazy on actual kernel driver bind or program exit.

2020-09-25 07:46 UTC, haiodo approved these changes

2020-09-25 07:47 UTC, merged